"""
protocol and performative constants
"""

NEGOTIATION_PROTOCOL = "NEGOTIATION_PROTOCOL"
BID_PROTOCOL = "BID" # Si usamos un manager

BID_ACCEPT_PERFORMATIVE = "ACCEPT"
BID_REFUSE_PERFORMATIVE = "REFUSE"
BID_OFFER_PERFORMATIVE = "OFFER"
NEGOTIATION_ACK_PERFORMATIVE = "ACK"
NEGOTIATION_END_PERFORMATIVE = "END"

# Simplified
JINN_READY = "JINN_READY"
JINN_WAITING = "JINN_SENDER_WAITING"
JINN_SENDER_WAITING = "JINN_SENDER_WAITING"
JINN_RECIVR_WAITING = "JINN_RECIVR_WAITING"
JINN_DONE = "JINN_DONE"

# Advanced
JINN_READY_TO_NEGOTIATE = "JINN_READY_TO_NEGOTIATE"
JINN_WAITING_OFFER_RESPONSE = "JINN_WAITING_OFFER_RESPONSE"
JINN_WAITING_ACCEPTANCE_RESPONSE = "JINN_WAITING_ACCEPTANCE_RESPONSE"
JINN_ACCEPTED_OFFER = "JINN_ACCEPTED_OFFER"
JINN_FINISHED_NEGOTIATION = "JINN_FINISHED_NEGOTIATION"

